language: perl

perl:
    - "5.19"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"

install:
    - dzil authordeps --missing | cpanm  --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps --author --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }

script:
    - dzil test --author --release
